### ISSUE TITLE
Error because of youtube-dl.js

### ISSUE THREAD

**Issue by TheComputerM** [lleellee0/youtube-downloader#1]
There is and error coming, maybe because of the build not passing of youtube-dl

Here is the error:

Uncaught Error: spawn UNKNOWN
    at exports._errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:505:9)
    at exports.execFile (child_process.js:220:15)
    at module.(anonymous function) (ELECTRON_ASAR.js:199:20)
    at call (E:\Mudit and Harshit\Projects\Local\Lightweight-Youtube-Downloader\node_modules\youtube-dl\lib\youtube-dl.js:163:5)
    at Function.getInfo (E:\Mudit and Harshit\Projects\Local\Lightweight-Youtube-Downloader\node_modules\youtube-dl\lib\youtube-dl.js:285:5)
    at module.exports (E:\Mudit and Harshit\Projects\Local\Lightweight-Youtube-Downloader\node_modules\youtube-dl\lib\youtube-dl.js:107:10)
    at Object.exports.download (E:\Mudit and Harshit\Projects\Local\Lightweight-Youtube-Downloader\node_modules\fyda\mp4\downloadMp4.js:13:15)
    at Object.<anonymous> (E:\Mudit and Harshit\Projects\Local\Lightweight-Youtube-Downloader\node_modules\fyda\app.js:8:5)

**Comment by SAYEDALISINA93** [comment]
I have the same issue.
The youtube-dl file is missing.
